---
all:
  vars:
    ansible_user: ubuntu
    ansible_become: yes
    ansible_become_method: sudo

postgresql_cluster:
  hosts:
    postgres-01:
      ansible_host: 192.168.60.103
      etcd_name: postgresql-01
      etcd_initial_cluster_state: new
      patroni_name: postgresql-01
    postgres-02:
      ansible_host: 192.168.60.104
      etcd_name: postgresql-02
      etcd_initial_cluster_state: new
      patroni_name: postgresql-02
    postgres-03:
      ansible_host: 192.168.60.105
      etcd_name: postgresql-03
      etcd_initial_cluster_state: new
      patroni_name: postgresql-03

haproxy_cluster:
  hosts:
    haproxy-01:
      ansible_host: 192.168.60.100
      keepalived_state: MASTER
      keepalived_priority: 100
      keepalived_interface: eth0
    haproxy-02:
      ansible_host: 192.168.60.101
      keepalived_state: BACKUP
      keepalived_priority: 90
      keepalived_interface: eth0
    haproxy-03:
      ansible_host: 192.168.60.102
      keepalived_state: BACKUP
      keepalived_priority: 80
      keepalived_interface: eth0

all_postgres:
  children:
    postgresql_cluster: {}

all_haproxy:
  children:
    haproxy_cluster: {}